### PR TITLE
Fixed Travis build, added AppVeyor + Badges

### PR DESCRIPTION
**Pull request by rerodrigues**
Hi @neekey!

Travis was failing on node 0.8 environment due to an unresolved dependency in NPM. To fix this, I've updated the node versions in the tests to the following:

- node: Latest NODEJS version (7)
- iojs: Latest IO.JS version
- 6: Current LTS version
- 4: Previous LTS version
- 0.12: Latest NODE version before IO.JS merge

I've also added AppVeyor integration for tests on Windows machines.

And just a little sugar, I've added the Travis and AppVeyor status badges on README.
The only caveat is that the AppVeyor badge is using my project ID, to fix this you need authorize your repo in AppVeyor and replace the ID in the badge.

cheers!

### CODE REVIEW

**Comment by neekey** [comment]
Hi @rerodrigues awesome work and thanks for introducing me a new product (AppVeyor).

Anyway, are you interested in becoming a maintainer of this Repo, since I haven't been using Grunt for a long time and you and your team are still actively using this module and Grunt.

If so, I will add you as a collaborator and grant you NPM permission, and you can keep on using your AppVeyor id ; )

Let me know if you are interested.

**Comment by rerodrigues** [comment]
Thanks @neekey!

Yes, you're right! We are using it actively! In fact grunt-multi is the key component of a new build system that I've created to integrate various of our projects in the same repo, using jenkins to generate different builds, hence the command-line options importance for us. And I can't see we stop using it anytime soon!

I'll be really glad to become a maintainer, it will be a pleasure!

**Comment by neekey** [comment]
@rerodrigues Awesome! I will add you as a maintainer soon, and just feel free to add your info into the maintainer list inside the `package.json` or `README.md`

**Comment by neekey** [comment]
@rerodrigues I just have added you as a maintainer, now you should be able to push code. Could you  give me your NPM account so that I can assign you the NPM permission.

**Comment by neekey** [comment]
@rerodrigues I also want to setup some basic development rules for the further development  https://github.com/neekey/grunt-multi/pull/9 could you take a look? Feel free to add rules you think are good to follow.

**Comment by rerodrigues** [comment]
Hi @neekey thanks for the invite. I've created a NPM user with the same ID of my github user `rerodrigues`

**Comment by neekey** [comment]
@rerodrigues I have already added you as the owner for the NPM package.

Anyway, because of some bad operation (https://github.com/neekey/grunt-multi/pull/11), I have to do some rebase to make the `0.0.7` branch a little bit cleaner and just created a PR for `0.0.7`

https://github.com/neekey/grunt-multi/pull/10

Since I don't have any more feature in mind for the next version, it's up to you how many features you want to put into the `0.0.7`.

**Comment by rerodrigues** [comment]
Great @neekey! 

I just added some sugar to the README, namely a 'Contributing' section and a fancy 'If you haven't used grunt before...' header. 

I think it's time for 0.0.7 to launch.

**Comment by neekey** [comment]
Great work 👍

**Pull request merged**
